# Netlify Configuration File
# Ensures proper sitemap handling

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    "Content-Type" = "application/xml"
    "Cache-Control" = "public, max-age=3600"  # 1 hour cache

[[headers]]
  for = "/robots.txt"
  [headers.values]
    "Content-Type" = "text/plain"
    "Cache-Control" = "public, max-age=86400"  # 24 hour cache
